baseURL = 'http://visd0m.dev/'
languageCode = 'en-us'
title = "visd0m.dev"
theme = 'PaperMod'

[markup.goldmark.renderer]
unsafe = true

[params.homeInfoparams]
content = """
Hi 👋!<br/>
I am visd0m and this is a blog about:
<li/> software development
<li/> videogames
<li/> emacs tips and tricks
<br/>
<br/>
Here is my <a rel="me" href="https://mastodon.social/@visd0m">Mastodon</a> link, follow me to stay up to date!
"""

[params.author]
name = "visd0m"

[[params.socialIcons]]
name = "github"
url = "https://github.com/visd0m"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/domenico-visconti-b6624b8b"